-- =====================================================
-- RAJMINES VTS - Oracle Database Schema
-- GPS-RFID Based Vehicle Tracking System
-- =====================================================

-- =====================================================
-- 1. VENDOR MANAGEMENT TABLES
-- =====================================================

-- GPS Vendor Registration Table
CREATE TABLE GPS_VENDOR (
    VENDOR_ID VARCHAR2(20) PRIMARY KEY,
    VENDOR_NAME VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    CONTACT_NO VARCHAR2(15) NOT NULL,
    ADDRESS VARCHAR2(500) NOT NULL,
    PINCODE VARCHAR2(10) NOT NULL,
    GST_NUMBER VARCHAR2(15) NOT NULL UNIQUE,
    PAN_NUMBER VARCHAR2(10) NOT NULL UNIQUE,
    CONTACT_PERSON_NAME VARCHAR2(100) NOT NULL,
    CONTACT_PERSON_NO VARCHAR2(15) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED')),
    OTP VARCHAR2(6),
    OTP_EXPIRY TIMESTAMP,
    OTP_VERIFIED CHAR(1) DEFAULT 'N' CHECK (OTP_VERIFIED IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    REMARKS VARCHAR2(500)
);

-- Vendor Documents Table
CREATE TABLE GPS_VENDOR_DOCUMENTS (
    DOC_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VENDOR_ID VARCHAR2(20) NOT NULL,
    DOCUMENT_TYPE VARCHAR2(50) NOT NULL, -- PAN, GST, LICENSE, etc.
    DOCUMENT_NAME VARCHAR2(200) NOT NULL,
    DOCUMENT_PATH VARCHAR2(500) NOT NULL,
    FILE_SIZE NUMBER,
    UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPLOADED_BY VARCHAR2(50),
    CONSTRAINT FK_VENDOR_DOC FOREIGN KEY (VENDOR_ID) REFERENCES GPS_VENDOR(VENDOR_ID)
);

-- =====================================================
-- 2. DEVICE MANAGEMENT TABLES
-- =====================================================

-- GPS Device Registration Table
CREATE TABLE GPS_DEVICE (
    DEVICE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_NAME VARCHAR2(100) NOT NULL,
    IMEI_SERIAL VARCHAR2(50) NOT NULL UNIQUE,
    MODEL VARCHAR2(100),
    FIRMWARE_VERSION VARCHAR2(50),
    SIM_ICCID VARCHAR2(50),
    SIM_MSISDN VARCHAR2(15),
    HEALTH_STATUS VARCHAR2(20) DEFAULT 'UNKNOWN' CHECK (HEALTH_STATUS IN ('HEALTHY', 'WARNING', 'CRITICAL', 'UNKNOWN')),
    DEVICE_STATUS VARCHAR2(20) DEFAULT 'REGISTERED' CHECK (DEVICE_STATUS IN ('REGISTERED', 'TESTED', 'FITTED', 'ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED')),
    VENDOR_ID VARCHAR2(20) NOT NULL,
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGISTERED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    REMARKS VARCHAR2(500),
    CONSTRAINT FK_DEVICE_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES GPS_VENDOR(VENDOR_ID)
);

-- Device Testing Table
CREATE TABLE GPS_DEVICE_TEST (
    TEST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID NUMBER NOT NULL,
    GPS_SIGNAL_STRENGTH VARCHAR2(20) NOT NULL CHECK (GPS_SIGNAL_STRENGTH IN ('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'NO_SIGNAL')),
    NETWORK_CONNECTIVITY VARCHAR2(20) NOT NULL CHECK (NETWORK_CONNECTIVITY IN ('CONNECTED', 'WEAK', 'DISCONNECTED')),
    BATTERY_STATUS VARCHAR2(20) NOT NULL CHECK (BATTERY_STATUS IN ('FULL', 'GOOD', 'LOW', 'CRITICAL')),
    DATA_TRANSMISSION VARCHAR2(20) NOT NULL CHECK (DATA_TRANSMISSION IN ('WORKING', 'INTERMITTENT', 'NOT_WORKING')),
    TEST_DATE_TIME TIMESTAMP NOT NULL,
    TESTER_NAME VARCHAR2(100) NOT NULL,
    TEST_LOCATION VARCHAR2(200),
    TEST_RESULT VARCHAR2(20) NOT NULL CHECK (TEST_RESULT IN ('PASSED', 'FAILED', 'CONDITIONAL')),
    TEST_NOTES CLOB,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TEST_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES GPS_DEVICE(DEVICE_ID)
);

-- Device Fitment & Activation Table
CREATE TABLE GPS_DEVICE_FITMENT (
    FITMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID NUMBER NOT NULL,
    VEHICLE_REG_NO VARCHAR2(20) NOT NULL,
    INSTALLATION_DATE_TIME TIMESTAMP NOT NULL,
    INSTALLER_NAME VARCHAR2(100) NOT NULL,
    INSTALLER_CONTACT VARCHAR2(15),
    ACTIVATION_STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (ACTIVATION_STATUS IN ('PENDING', 'ACTIVE', 'INACTIVE')),
    FIRST_GPS_PING_DATE TIMESTAMP,
    ACTIVATION_DATE TIMESTAMP,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_DATE TIMESTAMP,
    REMARKS VARCHAR2(500),
    CONSTRAINT FK_FITMENT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES GPS_DEVICE(DEVICE_ID),
    CONSTRAINT UK_FITMENT_VEHICLE UNIQUE (VEHICLE_REG_NO)
);

-- Device Fitment Photos Table
CREATE TABLE GPS_DEVICE_FITMENT_PHOTOS (
    PHOTO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FITMENT_ID NUMBER NOT NULL,
    PHOTO_NAME VARCHAR2(200) NOT NULL,
    PHOTO_PATH VARCHAR2(500) NOT NULL,
    FILE_SIZE NUMBER,
    UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PHOTO_FITMENT FOREIGN KEY (FITMENT_ID) REFERENCES GPS_DEVICE_FITMENT(FITMENT_ID)
);

-- Device Maintenance/Deactivation Table
CREATE TABLE GPS_DEVICE_MAINTENANCE (
    MAINTENANCE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID NUMBER NOT NULL,
    ACTION_TYPE VARCHAR2(20) NOT NULL CHECK (ACTION_TYPE IN ('MAINTENANCE', 'DEACTIVATE', 'REACTIVATE')),
    REASON VARCHAR2(50) NOT NULL CHECK (REASON IN ('MAINTENANCE', 'MALFUNCTION', 'THEFT', 'REPLACEMENT', 'OTHER')),
    NOTES CLOB,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'RESOLVED')),
    CREATED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MAINT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES GPS_DEVICE(DEVICE_ID)
);

-- =====================================================
-- 3. GEOFENCING TABLES
-- =====================================================

-- Geofence Master Table
CREATE TABLE GEO_FENCE (
    GEOFENCE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GEOFENCE_NAME VARCHAR2(200) NOT NULL,
    GEOFENCE_TYPE VARCHAR2(50) NOT NULL CHECK (GEOFENCE_TYPE IN ('LEASE_AREA', 'DEALER_LOCATION', 'ILLEGAL_MINING_AREA', 'WEIGHBRIDGE', 'OTHER')),
    LATITUDE NUMBER(10, 8) NOT NULL,
    LONGITUDE NUMBER(11, 8) NOT NULL,
    RADIUS_METERS NUMBER(10, 2) NOT NULL,
    TOLERANCE_RADIUS_METERS NUMBER(10, 2),
    ADDRESS VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_DATE TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    DESCRIPTION VARCHAR2(500)
);

-- Geofence Violation Log
CREATE TABLE GEO_FENCE_VIOLATION (
    VIOLATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GEOFENCE_ID NUMBER NOT NULL,
    DEVICE_ID NUMBER NOT NULL,
    VEHICLE_REG_NO VARCHAR2(20),
    VIOLATION_TYPE VARCHAR2(50) CHECK (VIOLATION_TYPE IN ('ENTRY', 'EXIT', 'DWELL_TIME_EXCEEDED')),
    LATITUDE NUMBER(10, 8) NOT NULL,
    LONGITUDE NUMBER(11, 8) NOT NULL,
    VIOLATION_DATE_TIME TIMESTAMP NOT NULL,
    DURATION_MINUTES NUMBER(10, 2),
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'ACKNOWLEDGED', 'RESOLVED')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_VIOLATION_GEOFENCE FOREIGN KEY (GEOFENCE_ID) REFERENCES GEO_FENCE(GEOFENCE_ID),
    CONSTRAINT FK_VIOLATION_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES GPS_DEVICE(DEVICE_ID)
);

-- =====================================================
-- 4. TRIP & TRACKING TABLES
-- =====================================================

-- Trip Master Table
CREATE TABLE TRIP_MASTER (
    TRIP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRIP_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    ERWANA_TRANSIT_PASS_NO VARCHAR2(100),
    VEHICLE_REG_NO VARCHAR2(20) NOT NULL,
    DEVICE_ID NUMBER NOT NULL,
    ORIGIN_LEASE_ID NUMBER,
    DESTINATION_DEALER_ID NUMBER,
    COMMODITY_TYPE VARCHAR2(100),
    COMMODITY_QUANTITY NUMBER(10, 2),
    DRIVER_NAME VARCHAR2(100),
    DRIVER_CONTACT VARCHAR2(15),
    EXPECTED_DEPARTURE_TIME TIMESTAMP,
    ACTUAL_DEPARTURE_TIME TIMESTAMP,
    EXPECTED_ARRIVAL_TIME TIMESTAMP,
    ACTUAL_ARRIVAL_TIME TIMESTAMP,
    WEIGHBRIDGE_ID NUMBER,
    ROUTE_DETAILS CLOB,
    TRIP_STATUS VARCHAR2(20) DEFAULT 'ASSIGNED' CHECK (TRIP_STATUS IN ('ASSIGNED', 'IN_PROGRESS', 'DELAYED', 'DEVIATED', 'COMPLETED', 'CANCELLED')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_DATE TIMESTAMP,
    REMARKS VARCHAR2(500),
    CONSTRAINT FK_TRIP_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES GPS_DEVICE(DEVICE_ID),
    CONSTRAINT FK_TRIP_ORIGIN FOREIGN KEY (ORIGIN_LEASE_ID) REFERENCES GEO_FENCE(GEOFENCE_ID),
    CONSTRAINT FK_TRIP_DEST FOREIGN KEY (DESTINATION_DEALER_ID) REFERENCES GEO_FENCE(GEOFENCE_ID)
);

-- GPS Tracking Data Table
CREATE TABLE GPS_TRACKING_DATA (
    TRACKING_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEVICE_ID NUMBER NOT NULL,
    TRIP_ID NUMBER,
    LATITUDE NUMBER(10, 8) NOT NULL,
    LONGITUDE NUMBER(11, 8) NOT NULL,
    SPEED_KMH NUMBER(5, 2),
    HEADING NUMBER(5, 2),
    ALTITUDE NUMBER(10, 2),
    GPS_ACCURACY NUMBER(5, 2),
    SATELLITE_COUNT NUMBER(2),
    BATTERY_LEVEL NUMBER(3),
    SIGNAL_STRENGTH NUMBER(3),
    TRACKING_DATE_TIME TIMESTAMP NOT NULL,
    RECEIVED_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(20) DEFAULT 'VALID' CHECK (STATUS IN ('VALID', 'INVALID', 'DUPLICATE')),
    CONSTRAINT FK_TRACKING_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES GPS_DEVICE(DEVICE_ID),
    CONSTRAINT FK_TRACKING_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIP_MASTER(TRIP_ID)
);

-- Trip Route Deviation Table
CREATE TABLE TRIP_ROUTE_DEVIATION (
    DEVIATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRIP_ID NUMBER NOT NULL,
    DEVIATION_TYPE VARCHAR2(50) CHECK (DEVIATION_TYPE IN ('ROUTE_DEVIATION', 'STOP_EXCEEDED', 'SPEED_VIOLATION', 'GEOFENCE_VIOLATION')),
    DEVIATION_DISTANCE_METERS NUMBER(10, 2),
    LATITUDE NUMBER(10, 8) NOT NULL,
    LONGITUDE NUMBER(11, 8) NOT NULL,
    DEVIATION_DATE_TIME TIMESTAMP NOT NULL,
    DURATION_MINUTES NUMBER(10, 2),
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'ACKNOWLEDGED', 'RESOLVED')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARKS VARCHAR2(500),
    CONSTRAINT FK_DEVIATION_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIP_MASTER(TRIP_ID)
);

-- Trip Stops Table
CREATE TABLE TRIP_STOPS (
    STOP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRIP_ID NUMBER NOT NULL,
    LATITUDE NUMBER(10, 8) NOT NULL,
    LONGITUDE NUMBER(11, 8) NOT NULL,
    STOP_START_TIME TIMESTAMP NOT NULL,
    STOP_END_TIME TIMESTAMP,
    DURATION_MINUTES NUMBER(10, 2),
    STOP_REASON VARCHAR2(200),
    IS_AUTHORIZED CHAR(1) DEFAULT 'N' CHECK (IS_AUTHORIZED IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_STOP_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIP_MASTER(TRIP_ID)
);

-- =====================================================
-- 5. NOTIFICATIONS TABLE
-- =====================================================

-- Notifications Master Table
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOTIFICATION_TYPE VARCHAR2(50) NOT NULL CHECK (NOTIFICATION_TYPE IN ('DELAY', 'ROUTE_DEVIATION', 'DEVICE_STATUS', 'GEOFENCE_VIOLATION', 'DEVICE_OFFLINE', 'TRIP_ALERT', 'SYSTEM_ALERT')),
    TITLE VARCHAR2(200) NOT NULL,
    MESSAGE CLOB NOT NULL,
    PRIORITY VARCHAR2(20) DEFAULT 'MEDIUM' CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    RECIPIENT_TYPE VARCHAR2(50) CHECK (RECIPIENT_TYPE IN ('SYSTEM_ADMIN', 'GPS_VENDOR', 'MINING_OPERATOR', 'ALL')),
    RECIPIENT_ID VARCHAR2(50), -- User ID or Role
    RELATED_ENTITY_TYPE VARCHAR2(50), -- DEVICE, TRIP, GEOFENCE, etc.
    RELATED_ENTITY_ID NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'SENT', 'READ', 'ACKNOWLEDGED')),
    EMAIL_SENT CHAR(1) DEFAULT 'N' CHECK (EMAIL_SENT IN ('Y', 'N')),
    IN_APP_SENT CHAR(1) DEFAULT 'Y' CHECK (IN_APP_SENT IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    READ_DATE TIMESTAMP,
    READ_BY VARCHAR2(50)
);

-- =====================================================
-- 6. AUDIT LOGS TABLE
-- =====================================================

-- Audit Logs Table
CREATE TABLE AUDIT_LOGS (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    USER_ROLE VARCHAR2(50) NOT NULL,
    ACTION_TYPE VARCHAR2(50) NOT NULL, -- CREATE, UPDATE, DELETE, VIEW, LOGIN, LOGOUT
    ENTITY_TYPE VARCHAR2(50) NOT NULL, -- VENDOR, DEVICE, TRIP, GEOFENCE, etc.
    ENTITY_ID VARCHAR2(50),
    OLD_VALUES CLOB,
    NEW_VALUES CLOB,
    IP_ADDRESS VARCHAR2(50),
    SESSION_ID VARCHAR2(100),
    ACTION_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARKS VARCHAR2(500)
);

-- =====================================================
-- 7. SYSTEM CONFIGURATION TABLES
-- =====================================================

-- System Configuration Table
CREATE TABLE SYSTEM_CONFIG (
    CONFIG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONFIG_KEY VARCHAR2(100) NOT NULL UNIQUE,
    CONFIG_VALUE VARCHAR2(500) NOT NULL,
    CONFIG_DESCRIPTION VARCHAR2(500),
    CONFIG_TYPE VARCHAR2(50) CHECK (CONFIG_TYPE IN ('STRING', 'NUMBER', 'BOOLEAN', 'JSON')),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP
);

-- Alert Thresholds Configuration
CREATE TABLE ALERT_THRESHOLDS (
    THRESHOLD_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ALERT_TYPE VARCHAR2(50) NOT NULL UNIQUE,
    THRESHOLD_VALUE NUMBER(10, 2) NOT NULL,
    UNIT VARCHAR2(20), -- MINUTES, METERS, KMH, etc.
    DESCRIPTION VARCHAR2(500),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP
);

-- =====================================================
-- 8. USER & ROLE MANAGEMENT (if needed)
-- =====================================================

-- User Master Table
CREATE TABLE SYSTEM_USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(500),
    USER_ROLE VARCHAR2(50) NOT NULL CHECK (USER_ROLE IN ('SYSTEM_ADMIN', 'GPS_VENDOR', 'MINING_OPERATOR')),
    VENDOR_ID VARCHAR2(20), -- If user is GPS Vendor
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'LOCKED')),
    LAST_LOGIN_DATE TIMESTAMP,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_DATE TIMESTAMP,
    CONSTRAINT FK_USER_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES GPS_VENDOR(VENDOR_ID)
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- GPS Device Indexes
CREATE INDEX IDX_DEVICE_VENDOR ON GPS_DEVICE(VENDOR_ID);
CREATE INDEX IDX_DEVICE_STATUS ON GPS_DEVICE(DEVICE_STATUS);
CREATE INDEX IDX_DEVICE_IMEI ON GPS_DEVICE(IMEI_SERIAL);

-- Tracking Data Indexes
CREATE INDEX IDX_TRACKING_DEVICE ON GPS_TRACKING_DATA(DEVICE_ID);
CREATE INDEX IDX_TRACKING_TRIP ON GPS_TRACKING_DATA(TRIP_ID);
CREATE INDEX IDX_TRACKING_DATETIME ON GPS_TRACKING_DATA(TRACKING_DATE_TIME);

-- Trip Indexes
CREATE INDEX IDX_TRIP_STATUS ON TRIP_MASTER(TRIP_STATUS);
CREATE INDEX IDX_TRIP_VEHICLE ON TRIP_MASTER(VEHICLE_REG_NO);
CREATE INDEX IDX_TRIP_DEVICE ON TRIP_MASTER(DEVICE_ID);

-- Notification Indexes
CREATE INDEX IDX_NOTIF_STATUS ON NOTIFICATIONS(STATUS);
CREATE INDEX IDX_NOTIF_RECIPIENT ON NOTIFICATIONS(RECIPIENT_TYPE, RECIPIENT_ID);
CREATE INDEX IDX_NOTIF_CREATED ON NOTIFICATIONS(CREATED_DATE);

-- Audit Log Indexes
CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOGS(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_DATETIME ON AUDIT_LOGS(ACTION_DATE_TIME);

-- Geofence Indexes
CREATE INDEX IDX_GEOFENCE_TYPE ON GEO_FENCE(GEOFENCE_TYPE);
CREATE INDEX IDX_GEOFENCE_STATUS ON GEO_FENCE(STATUS);

-- =====================================================
-- SEQUENCES (if not using IDENTITY columns)
-- =====================================================
-- Note: Oracle 12c+ supports IDENTITY columns, but if using older version, use sequences

-- Example sequence (if needed for older Oracle versions):
-- CREATE SEQUENCE SEQ_DEVICE_ID START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE SEQ_TRIP_ID START WITH 1 INCREMENT BY 1;

-- =====================================================
-- INITIAL DATA / SEED DATA
-- =====================================================

-- Insert Alert Thresholds
INSERT INTO ALERT_THRESHOLDS (ALERT_TYPE, THRESHOLD_VALUE, UNIT, DESCRIPTION) VALUES
('DEVICE_OFFLINE_MINUTES', 30, 'MINUTES', 'Alert when device is offline for more than 30 minutes');
INSERT INTO ALERT_THRESHOLDS (ALERT_TYPE, THRESHOLD_VALUE, UNIT, DESCRIPTION) VALUES
('ROUTE_DEVIATION_METERS', 500, 'METERS', 'Alert when vehicle deviates more than 500 meters from route');
INSERT INTO ALERT_THRESHOLDS (ALERT_TYPE, THRESHOLD_VALUE, UNIT, DESCRIPTION) VALUES
('STOP_DURATION_MINUTES', 30, 'MINUTES', 'Alert when vehicle stops for more than 30 minutes');
INSERT INTO ALERT_THRESHOLDS (ALERT_TYPE, THRESHOLD_VALUE, UNIT, DESCRIPTION) VALUES
('TRIP_DELAY_MINUTES', 60, 'MINUTES', 'Alert when trip is delayed by more than 60 minutes');

-- System Configuration
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESCRIPTION, CONFIG_TYPE) VALUES
('GPS_PING_INTERVAL', '60', 'GPS ping interval in seconds', 'NUMBER');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESCRIPTION, CONFIG_TYPE) VALUES
('DEVICE_ACTIVATION_TIMEOUT', '5', 'Device activation timeout in minutes after fitment', 'NUMBER');
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESCRIPTION, CONFIG_TYPE) VALUES
('OTP_EXPIRY_MINUTES', '10', 'OTP expiry time in minutes', 'NUMBER');

COMMIT;

-- =====================================================
-- END OF SCHEMA
-- =====================================================

